services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: install-dev
    command: bun run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - database
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events